name: talkr_chat_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 1.0.2
  flutter_bloc: 8.1.3
  go_router: 10.1.0
  dio: 5.3.2
  json_annotation: 4.8.1
  provider: 6.0.5
  get_it: 7.6.0
  shared_preferences: 2.2.0
  retrofit_generator: 7.0.8
  dartz: 0.10.1
  google_fonts: 5.1.0
  flutter_dotenv: 5.1.0
  equatable: 2.0.5
  change_app_package_name: 1.1.0
  retrofit: 4.0.1
  flutter_svg: 2.0.7
  firebase_core: 2.15.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0  
  build_runner:
  json_serializable: 6.7.1



flutter:

 
  uses-material-design: true

  
  assets:
    - assets/
    - assets/icons/
    - .env

